import cMyUI from './cMyUI';
export default class cMyUI_MainTab_create extends cMyUI {
    private readonly _idCreationOKButton;
    private readonly _idCreationExperienceGroupOfInfo;
    private readonly _idCreationDateExp;
    private readonly _idCreationQui;
    private readonly _idCreationFiles;
    private readonly _idCreationDivForMessageInfo;
    private readonly _idCreationExperienceNomPrefixe;
    private readonly _idCreationExperienceExperiencetype;
    private readonly _idCreationExperienceClef;
    private readonly _idCreationExperienceNumero;
    private readonly _My_Message_Classe;
    private readonly _idUpdateOKButton;
    private readonly _idUpdateInputExp;
    private readonly _idUpdateSelectOnchromosome1;
    private readonly _idUpdateSelectOnchromosome2;
    private readonly _idUpdateSelectOnchromosome3;
    private readonly _idUpdateSelectOnchromosome4;
    private readonly _idUpdateSelectOnTestType;
    private readonly _idUpdateSelectOnMarquage;
    private readonly _idUpdateSelectOnTerritoire;
    private readonly _idUpdateInputNbEchantillon;
    private readonly _idUpdateInputSGeneral;
    private readonly _idUpdateInputSComparatif;
    private readonly _idCreationExperience_drawInfoApresCreation;
    private readonly _nbGenotype;
    constructor();
    draw(): string;
    private drawCreateDialog;
    private drawUpdateDialog;
    drawInfoExperienceDialog(): string;
    addCallBackOnMyDialog(): void;
    private addCallBackOnMyDialog_ajout;
    private UpdateDeLaZONEBilanViSuDBApresCreateOuAjout;
    private addCallBackOnMyDialog_create;
    private lienExprienceId_NomManip;
    private checkFormContenu;
}
